const fs = require('fs')
const path = require('path')

const files = [
  'base/chain.js',
  'base/config.js',
  'base/constant.js',
  'base/element.js',
  'base/event.js',
  'base/global.js',
  'base/klass.js',
  'base/platform.js',
  'base/util.js',
  'util/event.js',
  'util/ajax/dwr.js',
  'util/ajax/jsonp.js',
  'util/ajax/message.js',
  'util/ajax/rest.js',
  'util/ajax/tag.js',
  'util/ajax/xdr.js',
  'util/animation/animation.js',
  'util/animation/bezier.js',
  'util/animation/bounce.js',
  'util/animation/decelerate.js',
  'util/animation/easein.js',
  'util/animation/easeinout.js',
  'util/animation/easeout.js',
  'util/animation/linear.js',
  'util/audio/audio.js',
  'util/cache/abstract.js',
  'util/cache/cache.js',
  'util/cache/cache.list.base.js',
  'util/cache/cache.list.js',
  'util/cache/cache.share.js',
  'util/cache/cookie.js',
  'util/cache/database.js',
  'util/cache/list.js',
  'util/cache/manager.js',
  'util/cache/share.js',
  'util/cache/storage.js',
  'util/calendar/calendar.js',
  'util/chain/NodeList.js',
  'util/chain/chainable.js',
  'util/chart/chart.js',
  'util/clipboard/clipboard.js',
  'util/clipper/clipper.js',
  'util/clock/clock.js',
  'util/color/color.js',
  'util/counter/counter.js',
  'util/cursor/cursor.js',
  'util/cycler/cycler.js',
  'util/dispatcher/dispatcher.2.js',
  'util/dispatcher/dispatcher.js',
  'util/dispatcher/module.base.js',
  'util/dispatcher/module.js',
  'util/dispatcher/regularModule.js',
  'util/dispatcher/test.js',
  'util/dragger/dragger.js',
  'util/dragger/simple.js',
  'util/editor/area.js',
  'util/editor/command.js',
  'util/editor/editor.js',
  'util/editor/text.js',
  'util/editor/toolbar.js',
  'util/effect/api.js',
  'util/effect/effect.api.js',
  'util/effect/effect.js',
  'util/encode/base64.js',
  'util/encode/crc32.js',
  'util/encode/json.js',
  'util/encode/md5.js',
  'util/encode/sha.md5.js',
  'util/es/array.js',
  'util/event/event.js',
  'util/file/paste.js',
  'util/file/save.js',
  'util/file/select.js',
  'util/flash/flash.js',
  'util/focus/focus.js',
  'util/form/form.js',
  'util/helper/select.js',
  'util/highlight/touch.js',
  'util/history/history.js',
  'util/history/history.override.js',
  'util/history/manager.js',
  'util/hover/hover.js',
  'util/lazy/image.js',
  'util/lazy/loading.js',
  'util/lightbox/lightbox.js',
  'util/list/holder.js',
  'util/list/module.js',
  'util/list/module.pager.js',
  'util/list/module.waterfall.js',
  'util/list/page.js',
  'util/list/waterfall.js',
  'util/media/audio.js',
  'util/media/flash.js',
  'util/media/media.js',
  'util/media/playlist.js',
  'util/page/base.js',
  'util/page/page.base.js',
  'util/page/page.js',
  'util/page/page.simple.js',
  'util/page/simple.js',
  'util/placeholder/placeholder.js',
  'util/query/nes.js',
  'util/query/query.js',
  'util/range/range.js',
  'util/region/region.zh.js',
  'util/region/zh.js',
  'util/resize/resize.js',
  'util/scroll/scroll.simple.js',
  'util/scroll/simple.js',
  'util/scroll/smart.js',
  'util/selector/cascade.js',
  'util/selector/range.js',
  'util/selector/selector.js',
  'util/selector/selector.range.js',
  'util/slider/simple.js',
  'util/slider/slider.js',
  'util/slider/slider.simple.js',
  'util/slider/slider.x.js',
  'util/slider/slider.xy.js',
  'util/slider/slider.y.js',
  'util/slider/x.js',
  'util/slider/xy.js',
  'util/slider/y.js',
  'util/sort/horizontal.js',
  'util/sort/sortable.js',
  'util/sort/vertical.js',
  'util/suggest/at.js',
  'util/suggest/suggest.js',
  'util/tab/tab.js',
  'util/tab/tab.view.js',
  'util/tab/view.js',
  'util/template/jst.js',
  'util/template/tpl.js',
  'util/template/trimpath.js',
  'util/timer/animation.js',
  'util/timer/interval.js',
  'util/toggle/toggle.js',
  'util/ajax/loader/html.js',
  'util/ajax/loader/loader.js',
  'util/ajax/loader/script.js',
  'util/ajax/loader/style.js',
  'util/ajax/loader/text.js',
  'util/ajax/proxy/flash.js',
  'util/ajax/proxy/frame.js',
  'util/ajax/proxy/proxy.js',
  'util/ajax/proxy/upload.js',
  'util/ajax/proxy/xhr.js',
  'util/data/portrait/portrait.js',
  'util/data/region/zh.js',
  'util/dispatcher/dsp/group.js',
  'util/dispatcher/dsp/node.js',
  'util/dispatcher/dsp/single.js',
  'util/dispatcher/dsp/util.js',
  'util/editor/command/backcolor.js',
  'util/editor/command/blockquote.js',
  'util/editor/command/bold.js',
  'util/editor/command/card.js',
  'util/editor/command/color.js',
  'util/editor/command/font.js',
  'util/editor/command/fontname.js',
  'util/editor/command/fontsize.js',
  'util/editor/command/forecolor.js',
  'util/editor/command/format.js',
  'util/editor/command/insertorderedlist.js',
  'util/editor/command/insertunorderedlist.js',
  'util/editor/command/italic.js',
  'util/editor/command/justifycenter.js',
  'util/editor/command/justifyleft.js',
  'util/editor/command/justifyright.js',
  'util/editor/command/link.js',
  'util/editor/command/removeformat.js',
  'util/editor/command/simple.js',
  'util/editor/command/space.js',
  'util/editor/command/strikethrough.js',
  'util/editor/command/superscript.js',
  'util/editor/command/underline.js',
  'util/editor/command/uploadimage.js',
]

let content = ''
let kvs = ''

for (let file of files) {
  const objName = file.replace(/\/|\./g, '_')
  const key = file.replace('.js', '')
  content += `const ${objName} = require('nej-commonjs/${key}'); \n`
  kvs += `'${key}': ${objName},\n`
}

content += `

const NEJ_MAP = {
${kvs}
}

`

fs.writeFileSync('./result.txt', content)